/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
*/
package org.apache.taverna.scufl2.wfdesc.ontologies; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/home/stain/src/incubator-taverna-language/taverna-scufl2-wfdesc/src/main/resources/com/xmlns/foaf/foaf.rdf 
 * @author Auto-generated by schemagen on 21 Nov 2018 10:58 
 */
public class Foaf {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://xmlns.com/foaf/0.1/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>Indicates an account held by this agent.</p> */
    public static final ObjectProperty account = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/account" );
    
    /** <p>Indicates a homepage of the service provide for this online account.</p> */
    public static final ObjectProperty accountServiceHomepage = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/accountServiceHomepage" );
    
    /** <p>A location that something is based near, for some broadly human notion of 
     *  near.</p>
     */
    public static final ObjectProperty based_near = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/based_near" );
    
    /** <p>A current project this person works on.</p> */
    public static final ObjectProperty currentProject = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/currentProject" );
    
    /** <p>A depiction of some thing.</p> */
    public static final ObjectProperty depiction = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/depiction" );
    
    /** <p>A thing depicted in this representation.</p> */
    public static final ObjectProperty depicts = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/depicts" );
    
    /** <p>An organization funding a project or person.</p> */
    public static final ObjectProperty fundedBy = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/fundedBy" );
    
    /** <p>Indicates an account held by this agent.</p> */
    public static final ObjectProperty holdsAccount = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/holdsAccount" );
    
    /** <p>A homepage for some thing.</p> */
    public static final ObjectProperty homepage = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/homepage" );
    
    /** <p>An image that can be used to represent some thing (ie. those depictions which 
     *  are particularly representative of something, eg. one's photo on a homepage).</p>
     */
    public static final ObjectProperty img = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/img" );
    
    /** <p>A page about a topic of interest to this person.</p> */
    public static final ObjectProperty interest = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/interest" );
    
    /** <p>A person known by this person (indicating some level of reciprocated interaction 
     *  between the parties).</p>
     */
    public static final ObjectProperty knows = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/knows" );
    
    /** <p>A logo representing some thing.</p> */
    public static final ObjectProperty logo = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/logo" );
    
    /** <p>Something that was made by this agent.</p> */
    public static final ObjectProperty made = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/made" );
    
    /** <p>An agent that made this thing.</p> */
    public static final ObjectProperty maker = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/maker" );
    
    /** <p>A personal mailbox, ie. an Internet mailbox associated with exactly one owner, 
     *  the first owner of this mailbox. This is a 'static inverse functional property', 
     *  in that there is (across time and change) at most one individual that ever 
     *  has any particular value for foaf:mbox.</p>
     */
    public static final ObjectProperty mbox = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/mbox" );
    
    /** <p>Indicates a member of a Group</p> */
    public static final ObjectProperty member = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/member" );
    
    /** <p>An OpenID for an Agent.</p> */
    public static final ObjectProperty openid = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/openid" );
    
    /** <p>A page or document about this thing.</p> */
    public static final ObjectProperty page = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/page" );
    
    /** <p>A project this person has previously worked on.</p> */
    public static final ObjectProperty pastProject = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/pastProject" );
    
    /** <p>A phone, specified using fully qualified tel: URI scheme (refs: http://www.w3.org/Addressing/schemes.html#tel).</p> */
    public static final ObjectProperty phone = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/phone" );
    
    /** <p>The primary topic of some page or document.</p> */
    public static final ObjectProperty primaryTopic = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/primaryTopic" );
    
    /** <p>A link to the publications of this person.</p> */
    public static final ObjectProperty publications = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/publications" );
    
    /** <p>A homepage of a school attended by the person.</p> */
    public static final ObjectProperty schoolHomepage = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/schoolHomepage" );
    
    /** <p>A theme.</p> */
    public static final ObjectProperty theme = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/theme" );
    
    /** <p>A derived thumbnail image.</p> */
    public static final ObjectProperty thumbnail = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/thumbnail" );
    
    /** <p>A tipjar document for this agent, describing means for payment and reward.</p> */
    public static final ObjectProperty tipjar = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/tipjar" );
    
    /** <p>A topic of some page or document.</p> */
    public static final ObjectProperty topic = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/topic" );
    
    /** <p>A thing of interest to this person.</p> */
    public static final ObjectProperty topic_interest = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/topic_interest" );
    
    /** <p>A weblog of some thing (whether person, group, company etc.).</p> */
    public static final ObjectProperty weblog = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/weblog" );
    
    /** <p>A work info homepage of some person; a page about their work for some organization.</p> */
    public static final ObjectProperty workInfoHomepage = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/workInfoHomepage" );
    
    /** <p>A workplace homepage of some person; the homepage of an organization they 
     *  work for.</p>
     */
    public static final ObjectProperty workplaceHomepage = M_MODEL.createObjectProperty( "http://xmlns.com/foaf/0.1/workplaceHomepage" );
    
    /** <p>Indicates the name (identifier) associated with this online account.</p> */
    public static final DatatypeProperty accountName = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/accountName" );
    
    /** <p>The age in years of some agent.</p> */
    public static final DatatypeProperty age = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/age" );
    
    /** <p>An AIM chat ID</p> */
    public static final DatatypeProperty aimChatID = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/aimChatID" );
    
    /** <p>The birthday of this Agent, represented in mm-dd string form, eg. '12-31'.</p> */
    public static final DatatypeProperty birthday = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/birthday" );
    
    /** <p>A checksum for the DNA of some thing. Joke.</p> */
    public static final DatatypeProperty dnaChecksum = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/dnaChecksum" );
    
    /** <p>The family name of some person.</p> */
    public static final DatatypeProperty familyName = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/familyName" );
    
    /** <p>The family name of some person.</p> */
    public static final DatatypeProperty family_name = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/family_name" );
    
    /** <p>The first name of a person.</p> */
    public static final DatatypeProperty firstName = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/firstName" );
    
    /** <p>A textual geekcode for this person, see http://www.geekcode.com/geek.html</p> */
    public static final DatatypeProperty geekcode = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/geekcode" );
    
    /** <p>The gender of this Agent (typically but not necessarily 'male' or 'female').</p> */
    public static final DatatypeProperty gender = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/gender" );
    
    /** <p>The given name of some person.</p> */
    public static final DatatypeProperty givenName = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/givenName" );
    
    /** <p>The given name of some person.</p> */
    public static final DatatypeProperty givenname = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/givenname" );
    
    /** <p>An ICQ chat ID</p> */
    public static final DatatypeProperty icqChatID = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/icqChatID" );
    
    /** <p>A jabber ID for something.</p> */
    public static final DatatypeProperty jabberID = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/jabberID" );
    
    /** <p>The last name of a person.</p> */
    public static final DatatypeProperty lastName = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/lastName" );
    
    /** <p>The sha1sum of the URI of an Internet mailbox associated with exactly one 
     *  owner, the first owner of the mailbox.</p>
     */
    public static final DatatypeProperty mbox_sha1sum = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/mbox_sha1sum" );
    
    /** <p>An MSN chat ID</p> */
    public static final DatatypeProperty msnChatID = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/msnChatID" );
    
    /** <p>A Myers Briggs (MBTI) personality classification.</p> */
    public static final DatatypeProperty myersBriggs = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/myersBriggs" );
    
    /** <p>A name for some thing.</p> */
    public static final DatatypeProperty name = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/name" );
    
    /** <p>A short informal nickname characterising an agent (includes login identifiers, 
     *  IRC and other chat nicknames).</p>
     */
    public static final DatatypeProperty nick = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/nick" );
    
    /** <p>A .plan comment, in the tradition of finger and '.plan' files.</p> */
    public static final DatatypeProperty plan = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/plan" );
    
    /** <p>A sha1sum hash, in hex.</p> */
    public static final DatatypeProperty sha1 = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/sha1" );
    
    /** <p>A Skype ID</p> */
    public static final DatatypeProperty skypeID = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/skypeID" );
    
    /** <p>A string expressing what the user is happy for the general public (normally) 
     *  to know about their current activity.</p>
     */
    public static final DatatypeProperty status = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/status" );
    
    /** <p>The surname of some person.</p> */
    public static final DatatypeProperty surname = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/surname" );
    
    /** <p>Title (Mr, Mrs, Ms, Dr. etc)</p> */
    public static final DatatypeProperty title = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/title" );
    
    /** <p>A Yahoo chat ID</p> */
    public static final DatatypeProperty yahooChatID = M_MODEL.createDatatypeProperty( "http://xmlns.com/foaf/0.1/yahooChatID" );
    
    /** <p>Indicates the class of individuals that are a member of a Group</p> */
    public static final AnnotationProperty membershipClass = M_MODEL.createAnnotationProperty( "http://xmlns.com/foaf/0.1/membershipClass" );
    
    /** <p>A document that this thing is the primary topic of.</p> */
    public static final OntProperty isPrimaryTopicOf = M_MODEL.createOntProperty( "http://xmlns.com/foaf/0.1/isPrimaryTopicOf" );
    
    /** <p>An agent (eg. person, group, software or physical artifact).</p> */
    public static final OntClass Agent = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/Agent" );
    
    /** <p>A document.</p> */
    public static final OntClass Document = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/Document" );
    
    /** <p>A class of Agents.</p> */
    public static final OntClass Group = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/Group" );
    
    /** <p>An image.</p> */
    public static final OntClass Image = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/Image" );
    
    /** <p>A foaf:LabelProperty is any RDF property with texual values that serve as 
     *  labels.</p>
     */
    public static final OntClass LabelProperty = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/LabelProperty" );
    
    /** <p>An online account.</p> */
    public static final OntClass OnlineAccount = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/OnlineAccount" );
    
    /** <p>An online chat account.</p> */
    public static final OntClass OnlineChatAccount = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/OnlineChatAccount" );
    
    /** <p>An online e-commerce account.</p> */
    public static final OntClass OnlineEcommerceAccount = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/OnlineEcommerceAccount" );
    
    /** <p>An online gaming account.</p> */
    public static final OntClass OnlineGamingAccount = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/OnlineGamingAccount" );
    
    /** <p>An organization.</p> */
    public static final OntClass Organization = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/Organization" );
    
    /** <p>A person.</p> */
    public static final OntClass Person = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/Person" );
    
    /** <p>A personal profile RDF document.</p> */
    public static final OntClass PersonalProfileDocument = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/PersonalProfileDocument" );
    
    /** <p>A project (a collective endeavour of some kind).</p> */
    public static final OntClass Project = M_MODEL.createClass( "http://xmlns.com/foaf/0.1/Project" );
    
}
